config/routes.rb
Myapp::Application.routes.draw do
  resources :products


  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"},
                     controllers: {omniauth_callbacks: "omniauth_callbacks", 
                     			   registrations: "registrations"},
                     :sign_out_via => [ :post, :delete ]

  root to: 'accounts#index'

match "invite_user" => "accounts#invite_user", as: 'invite_user'
get "accounts/vision" => "accounts#vision", as: "vision"

  
  resources :users

  resources :accounts do 
    get :settings
    resources :metrics
  end



  resources :products do
    resources :concepts do 
      resources :assumptions
    end
  end
end

app/models/concept.rb
class Concept < ActiveRecord::Base
	after_initialize :default_values

	belongs_to :user
	belongs_to :account
	belongs_to :product
	has_many :assumptions
	has_many :metrics, as: :metricable

	attr_accessible :title, :description, :impact, :state, :assumptions_attributes, :account_id, :user_id
	
	validates_presence_of :title
	accepts_nested_attributes_for :assumptions, :allow_destroy => true




	  private
  def default_values
    self.state ||= "DEFINE"
  end
end

app/controllers/concepts_controller.rb
class ConceptsController <ApplicationController
	before_filter :find_concept, only: [:show, :update, :edit]

	def new
		@product = Product.find(params[:product_id])
		@concept = @product.concepts.build
	end

	def create
		@product = Product.find(params[:product_id])
	    @concept = @product.concepts.new(params[:concept])
	    respond_to do |format|
	      if @concept.save
	        #add the original poster as a feature user. 
	        format.html { redirect_to edit_product_concept_path(@product, @concept) }
	      else
	        render "new"
	      end
	    end
	  end

	def edit
		@product = @concept.product
	end


	def show
		@account = current_account
		@product = @concept.product
		@assumptions = @concept.assumptions
	end

	def update
    respond_to do |format|
      if @concept.update_attributes(params[:concept])
        format.html { redirect_to :back }
        format.js {}
      else
        render action: "edit" 
      end
    end
 	end

 	def destroy
 		@concept = Concept.find(params[:id])
    @concept.destroy
    respond_to do |format|
      format.html {redirect_to :back}
      format.js
 		end
 	end
 	
 	private
  def find_concept
  	@concept = Concept.find(params[:id])
  end
end

app/views/concepts/_concept.html.erb
<tr>
<td>
<%= link_to concept.title, product_concept_path(@product, concept) %>
</td>
<td>
<%= concept.state %>
</td>
<td>
	<%= link_to "X", [@product, concept], :method => :delete, :class => 'btn btn-mini btn-danger' %>
</td>
</tr>

app/views/concepts/_state.html.erb
<li>
<%= simple_form_for @concept, url: product_concept_path(@product) do |f| %>
<%=	f.hidden_field :state, value: "DEFINE" %>
<%= f.submit "DEFINE", class: "btn #{'disabled' if @concept.state == 'DEFINE'}" %>
<% end %>
</li>
<li>
<%= simple_form_for @concept, url: product_concept_path(@product) do |f| %>
<%=	f.hidden_field :state, value: "VALIDATE" %>
<%= f.submit "VALIDATE", class: "btn #{'disabled' if @concept.state == 'VALIDATE'}" %>
<% end %>
</li>
<li>
<%= simple_form_for @concept, url: product_concept_path(@product) do |f| %>
<%=	f.hidden_field :state, value: "RESULTS" %>
<%= f.submit "RESULTS", class: "btn #{'disabled' if @concept.state == 'RESULTS'}" %>
<% end %>
</li>

app/views/concepts/edit.html.erb
<div class="container">
  <div class="status"></div>
  <br>
  <div class="row" id="feature-row">
    <div class="span8 offset2">
      <div class="feature-inner">
        <%= simple_form_for(@concept, url: product_concept_path(@product), method: :put) do |f| %>
          <%= f.input :title, input_html: {class: "span8"}, placeholder: "add your title", label: false, as: :text, autofocus: true%>
          <%= f.input :description, input_html: {class: "span8"}, placeholder: "add your description", label: false, as: :text, autofocus: true%>
          <%= f.input :impact, input_html: {class: "span8"}, placeholder: "add your impact", label: false, as: :text, autofocus: true%>
          <%= f.button :submit, 'Update Concept' %>
        <% end %>
         </div>
      </div>
    </div>
  </div>
</div>

app/views/concepts/new.html.erb
<div class="container">
  <div class="status"></div>
  <br>
  <div class="row" id="feature-row">
    <div class="span8 offset2">
      <div class="feature-inner">
        <%= simple_form_for(@concept, :url => product_concepts_path(@product, @concept), :html => { :method => :post }) do |f| %>
          <%= f.input :title, input_html: {class: "span8"}, placeholder: "add your title", label: false, as: :text, autofocus: true%>
          <%= f.input :description, input_html: {class: "span8"}, placeholder: "add your description", label: false, as: :text%>
          <%= f.hidden_field :user_id, value: "#{current_user.id}" %>
          <%= f.hidden_field :account_id, value: "#{current_account.id}" %>
          <%= f.input :impact, input_html: {class: "span8"}, placeholder: "add your impact", label: false, as: :text, autofocus: false%>
          <%= f.button :submit, 'Create Concept' %>
        <% end %>
         </div>
      </div>
    </div>
  </div>
</div>

app/views/concepts/show.html.erb
<div class="container">
	<div class="row">
		<div class="span9">
			<ol class="breadcrumb">
				<li>
		  		<%=link_to 'home', root_path%>
		  		<span class="divider">|</span>  
		  	</li> 
		  	<li>
		  	<%=link_to_unless_current(@concept.product.name, @product)%> 
		  	<span class="divider">|</span>  
		  	</li>
		  	<li>
		  		<%=link_to_unless_current(@concept.title, product_concept_path(@product,@concept))%>
		  		<span class="divider">|</span>   
		  	</li>
			</ol>
			<div class="progression">
				<ol class="inline">
				<%=render partial: 'concepts/state' %>
				</ol>
			</div>
			<div class="content-container ">
			<div class="content-header"></div>
				<div class="content-content">
					<table class="table table-striped">
					<th>Assumption</th>
					<th>State</th>
						<%= render @assumptions %>
					</table>
					<%= render partial: 'shared/assumptions_form', locals: {resource: @concept} %>
					<%= content_tag :a, 'Edit Assumptions', :href => "#assumptions-window", class: "btn metric-button", data: {toggle: 'modal'} %>
				</div>
			</div>
		</div>
	</div>
</div>
	


			