config/routes.rb
Myapp::Application.routes.draw do
  resources :products


  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"},
                     controllers: {omniauth_callbacks: "omniauth_callbacks", 
                     			   registrations: "registrations"},
                     :sign_out_via => [ :post, :delete ]

  root to: 'accounts#index'

match "invite_user" => "accounts#invite_user", as: 'invite_user'
get "accounts/vision" => "accounts#vision", as: "vision"

  
  resources :users

  resources :accounts do 
    get :settings
    resources :metrics
  end



  resources :products do
    resources :concepts do 
      resources :assumptions
    end
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
	# before_save :assign_account_and_user
  
  belongs_to :account
  belongs_to :user
  has_many :metrics, as: :metricable
  has_many :goals
  has_many :concepts

  attr_accessible :name, :concepts_attributes, :metrics_attributes

  accepts_nested_attributes_for :metrics, :allow_destroy => true
  accepts_nested_attributes_for :goals
  accepts_nested_attributes_for :concepts, :allow_destroy => true
  

  # def assign_account_and_user
  # 	self.account_id = current_account.id
  #   self.user_id    = current_user.id
  # end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	before_filter :find_product, only: [:update, :show]

	def new
		@product = current_user.account.products.new
	end

	def create
		@product = current_user.account.products.create(params[:product])
		respond_to do |format|
			if @product.save
				format.html { redirect_to edit_product_path(@product) }
			end
		end
	end

	def show
		@product  = Product.find(params[:id])
		@account  = current_account
		@concepts = @product.concepts
		@metrics  = @product.metrics
	end

	def update
    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to :back }
        format.js {}
        
      else
        render action: "edit" 
      end
    end
 	end

  def find_product
  	@product = Product.find(params[:id])
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_product.html.erb
<div class="span3">
	<div class="content-container">
		<div class="content-header">
		<%= link_to product.name, product %>
		</div>
		<div class="content-content">
			<h4> Metrics </h4>
			<ul>
				<% product.metrics.each do |f| %>
					<li>
						<%= f.value %>
					</li>
				<% end %>
			</ul>
			<h4> Goals </h4>
			<ul>
				<% product.goals.each do |f| %>
					<li>
						<%= f.value %>
					</li>
				<% end %>
			</ul>
			<h4> Concept Tests: <%=product.concepts.count%> </h4>
			<ul>
				<% product.concepts.each do |f| %>
					<li>
						<%= link_to f.title, product_concept_path(product, f) %>
						<br>
					</li>
				<% end %>
			</ul>
		</div>
	</div>
</div>

app/views/products/edit.html.erb
edit product

app/views/products/new.html.erb
<div class="container">
  <div class="status"></div>
  <br>
  <div class="row" id="feature-row">
    <div class="span8 offset2">
      <div class="feature-inner">
        <%= simple_form_for(@product, :html => { :method => :post }) do |f| %>
          <%= f.input :name, input_html: {class: "span8"}, placeholder: "Product Name", label: false, as: :text, autofocus: true%>
          <%= f.button :submit, 'Create Product' %>
        <% end %>
         </div>
      </div>
    </div>
  </div>
</div>

app/views/products/show.html.erb
<div class="container">
	<div class="row">
		<div class="span6">
		<ol class="breadcrumb">
			<li>
	  		<%=link_to 'home', root_path%>
	  		<span class="divider">|</span>  
	  	</li> 
	  	<li class="active">
	  	<%=link_to_unless_current(@product.name, @product)%> </li>
	  	<span class="divider">|</span>  
		</ol>
			<h2><%= @product.name %> </h2>
			<br>
		</div>
		</div>
	</div>
	<div class="container">
		<div class="row">
			<div class="span7">
				<div class="content-container ">
					<div class="content-header">Metrics</div>
					<div class="content-content">
						<%= render partial: @metrics %>	
						<%= render partial: 'shared/metrics_form', locals: {resource: @product} %>
						<%= content_tag :a, 'Edit Metrics', :href => "#metrics-window", class: "btn metric-button", data: {toggle: 'modal'} %>
					</div>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="span7">
				<div class="content-container">
					<div class="content-header">Concepts</div>
					<div class="content-content">
						<%= render partial: 'shared/concepts_form', locals: {resource: @product} %> 
						<table class="table	table-striped table-hover concept-table">
							<th class="span3">Name</th>
							<th class="span1">State</th>
							<th class="span1"><%= link_to 'new concept', new_product_concept_path(@product), class: 'btn btn-success' %></th>
							<%= content_tag :a, 'Add Concept', :href => "#concepts-window", class: "btn metric-button", data: {toggle: 'modal'} %>
							<%= render partial: @concepts %>
						</table>
					</div>
				</div>
			</div>
		</div>
	</div>