config/routes.rb
Myapp::Application.routes.draw do
  resources :products


  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"},
                     controllers: {omniauth_callbacks: "omniauth_callbacks", 
                     			   registrations: "registrations"},
                     :sign_out_via => [ :post, :delete ]

  root to: 'accounts#index'

match "invite_user" => "accounts#invite_user", as: 'invite_user'
get "accounts/vision" => "accounts#vision", as: "vision"

  
  resources :users

  resources :accounts do 
    get :settings
    resources :metrics
  end



  resources :products do
    resources :concepts do 
      resources :assumptions
    end
  end
end

app/views/layouts/_navbar.html.erb
<div class="navbar">
  <div class="navbar-inner">
    <div class="container">
      <% unless user_signed_in?%>
      <div class="navbar-content">
        <a class="brand" href="/">Featyre </a>
        <form class="navbar-search">
          <input type="text" class="search-query" placeholder="Search..."> 
        </form>
        <ul class="nav">
          <li>
          <a href="">Explore</a> 
          </li>
          <li>
          <a href="#">About</a> 
          </li>
        </ul>
        <ul class="nav" id="userlinks" style="float: right">
          <li>
            <%= link_to "Sign Up", new_user_registration_path %>
          </li>
          <li>
          <%= link_to "Login", new_user_session_path %>
          </li>
        </ul>
      </div>
      <% else %>
        
        <div class="navbar-content">
        <a class="brand" href="/">F </a>
          <form class="navbar-search">
            <input type="text" class="search-query" placeholder="Search..."> 
          </form>
          <ul class="nav">
            <li>
            <%= link_to "Settings", account_settings_path(current_account) %>
            </li>
          </ul>
          <ul id="user-links" class="navbar pull-right inline">
            <li>
              <%= image_tag current_user.avatar_url, size: "30x30"%>
            </li>
            <li>
              <%= current_user.name %>
            </li>
            <li>
            <a class="btn btn-primary" a href="/users/logout" data-method="delete" rel="nofollow">logout</a>
            </li>
          </ul>
        </div> <!-- navbar-content  -->
      <% end %>
    </div> <!-- container  -->
  </div> <!-- navbar-inner  -->
</div> <!-- navbar-fixed-top  -->

app/views/layouts/_responsive.html.erb
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Featyre" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->
    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
            <script type="text/javascript" src="//use.typekit.net/mxy2kva.js"></script>
        <script type="text/javascript">try{Typekit.load();}catch(e){}</script>
        <%= render "layouts/responsive" %>

  </head>
  <body>
    <%= render "layouts/navbar" %>
    <div class="container">
    <div class="status"></div>
      <%= bootstrap_flash %>
      <%= yield %> 
    </div>
  </body>     
  <%= javascript_include_tag "application" %>
  <footer>
  </footer>
</html>