config/routes.rb
Myapp::Application.routes.draw do
  resources :products


  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"},
                     controllers: {omniauth_callbacks: "omniauth_callbacks", 
                     			   registrations: "registrations"},
                     :sign_out_via => [ :post, :delete ]

  root to: 'accounts#index'

match "invite_user" => "accounts#invite_user", as: 'invite_user'
get "accounts/vision" => "accounts#vision", as: "vision"

  
  resources :users

  resources :accounts do 
    get :settings
    resources :metrics
  end



  resources :products do
    resources :concepts do 
      resources :assumptions
    end
  end
end

app/models/account.rb
class Account < ActiveRecord::Base
  
  # Associations
  has_many :users, dependent: :destroy
  has_many :products, dependent: :destroy
  has_many :concepts, dependent: :destroy
  has_many :metrics, as: :metricable

  #Attributes
	attr_accessible :company, :products_attributes, :metrics_attributes, :vision

  accepts_nested_attributes_for :metrics, :allow_destroy => true
  accepts_nested_attributes_for :users
  accepts_nested_attributes_for :products

  attr_accessor :owner_type
  attr_accessor :owner_id
end

app/controllers/accounts_controller.rb
class AccountsController <ApplicationController
before_filter :authenticate_user!

  def new
    @account = current_account
    @account.metrics.build
  end

  def index
    
    if current_user
      @user = current_user
      @account = current_user.account
      @products = @account.products
      @users = current_user.account.users
      @metrics = @account.metrics
    end
  end
  
  def invite_user
  	account = 	current_account
  	email = 	params[:account][:user][:email]
  	name =		params[:account][:user][:name]

  	user = User.find_or_create_by_email(account, name, email)
  	respond_to do |format|
  		format.html {redirect_to :back}

  		#add user to account and invite them
  	end
  end

  def settings
    @user = current_user
    @account = current_account
    @users = current_user.account.users
  end

  def update
    @account = current_account
    respond_to do |format|
      if @account.update_attributes(params[:account])
        format.html { redirect_to :back }
        format.js
      end
    end
  end

  def vision
    @account = current_account
    respond_to do |format|
      format.html { redirect_to :back }
      format.js {}
    end
  end

end

app/views/accounts/_invite.html.erb
<%= simple_form_for @account, url: invite_user_path() do |a| %>
	<%= a.simple_fields_for :user do |f| %>
		<%= f.input :name, label: false, placeholder: 'name' %>
		<%= f.input :email, label: false, placeholder: 'email' %>
		<%= f.button :submit, :value => 'Add Team Member' %>
	<% end %>
<% end %>

app/views/accounts/_metrics_form.html.erb
<div id="metrics-window" class="modal hide fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"> 
					<div class="modal-header">
						<button type="button" class="close" data-dismiss="modal" aria-hidden="true">x</button> 
						<h3> Team Metrics</h3>
					</div>
					<div class="modal-body">
						<%= simple_nested_form_for(@account, :wrapper => false) do |f| %>
							<%= f.fields_for :metrics do |m| %>
								<%= m.text_field :value, label: false, placeholder: "add metric"%>
								<%= m.link_to_remove "X" %>
							<% end %>
							<%= f.link_to_add "add metric", :metrics %>
					</div>
					<div class="modal-footer"> 
					<%= f.button :submit, 'Save Metrics'%>
					<% end %>
					</div>
				</div>

app/views/accounts/_vision_form.html.erb
<div id="modal-window" class="modal hide fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"> 
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">x</button> 
		<h3> Vision Statement</h3>
	</div>
	<div class="modal-body">
		<%= simple_form_for(@account, method: :put) do |f| %>
		<%= f.input :vision, label: false, placeholder: "add team vision" %>
	</div>
	<div class="modal-footer"> 
		<%= f.button :submit, "Update Vision" %>
		<% end %>
	</div>
</div>

app/views/accounts/index.html.erb
<div class="container account">
	<div class="row">
		<div class="span9 offset2">
			<div class="team-name"> <%= @account.company %> Product Team </div>
			<br>

			<div class="content-container">
				<div class="content-header">Vision</div>
				<div class="content-content" id="vision">
					<% if @account.vision.blank? %>
						<%= content_tag :a, 'Add Vision Statement', :href => "#modal-window", class: "btn", data: {toggle: 'modal'} %>
					<% else %>
						" <%= @account.vision  %> "
					<% end %>
				</div>
				<%= render partial: 'accounts/vision_form' %>
			</div>

			<div class="content-container ">
				<div class="content-header">Metrics</div>
				<div class="content-content">
					<%= render partial: @metrics %>
					<%= content_tag :a, 'Edit Metrics', :href => "#metrics-window", class: "btn metric-button", data: {toggle: 'modal'} %>
				</div>
				<%= render partial: 'shared/metrics_form', locals: {resource: @account} %>
			</div>
			<hr>
			<div class="stats">
				<div class="row">
					<div class="span3">
					Products: <%=@account.products.count %>
					</div>
					<div class="span3">
					Concepts: <%=@account.concepts.count %>
					</div>
					<div class="span3">
					Tests: <%=@account.concepts.where(state: 'testing').count %>
					</div>
				</div>
			</div>
			<hr>
				<div class="row">
					<div class="span12" style="margin-left: 0px">
						<%= render @products %>
					</div>
				</div>
			<div class="row span9">
			<%= button_to 'add product', new_product_path, method: :get%>
			</div>
		</div>
	</div>
</div>

app/views/accounts/settings.html.erb
<h2> Vision Statement </h2>
<%= simple_form_for(@account, method: :put) do |f| %>
 <%= f.input :vision %>
 <%= f.button :submit, "Edit Vision" %>
 <% end %>

<h2> Users </h2>
<ul>
<% @account.users.each do |f| %>

<li class="inline-block">
<%= f.name %>
<%= f.email %>
<% unless f.account_owner == true %>
<%= link_to "X", f, :method => :delete, :class => 'btn btn-mini btn-danger'%>
<% end %>
</li>
<% end %>
</ul>

<%= render partial: "invite" %>

app/views/accounts/static.html.erb
<%= @user.account_owner %>
<br>
<%= @user.email %>
<br>
<%= @user.account.company %>
<br>
<%= @user.account.users %>





<br>

<br>

<%= render partial: "invite" %>

app/views/accounts/update.js.erb
update.js.erb

app/views/accounts/users.html.erb
<% if current_user %>
<ul>
<% @account.users.each do |f| %>
<li class="inline-block">
<%= f.name %>
<%= f.email %>
</li>
<% end %>
</ul>

<%= render partial: "invite" %>
<% end %>